package co.feip.fefu2025

class Constants {
    companion object {
        val languages = arrayOf(
            "Python",
            "Java",
            "C++",
            "Kotlin",
            "Go",
            "C",
            "JS",
            "C#",
            "PHP",
            "R",
            "SQL",
            "Swift",
            "Perl",
            "ASM",
            "Ruby",
            "VB",
            "Rust",
            "ObjC",
            "Dart",
            "D",
            "COBOL",
            "Julia",
            "Scala",
            "Scheme",
            "Ada",
            "Lisp",
            "Apex",
            "Lua",
            "Fortran",
            "Haskell",
            "TS",
            "Algol",
            "Bash",
            "Carbon",
            "Curl",
            "Elixir",
            "F#",
            "ML",
            "OCaml",
            "OpenCL",
            "Zig",
            )
    }
}